fix: use esm to import monaco namespace. #53
alauda/ng-monaco-editor pull request #54
Opened 2021-05-01 16:38 UTC by fengtianze

2021-05-01 16:54 UTC, JounQin requested changes

2021-05-01 16:54 UTC, JounQin commented on src/monaco-common-editor.component.ts
> +import * as monacoEditor from 'monaco-editor/esm/vs/editor/editor.api';
统一一下从 typings 导入？

2021-05-02 02:44 UTC, fengtianze commented on src/monaco-common-editor.component.ts
> +import * as monacoEditor from 'monaco-editor/esm/vs/editor/editor.api';
没找到写法，这是一个namespace，不知道怎么再从typing导出。能改成全局类型也行

2021-05-02 03:23 UTC, JounQin approved these changes

2021-05-02 03:25 UTC, merged